# Generated by Django 6.0 on 2026-01-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='class_name',
            field=models.CharField(default='Class 1', max_length=50),
            preserve_default=False,
        ),
    ]
