# Generated by Django 6.0 on 2026-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academic/'),
        ),
    ]
