# Generated by Django 6.0 on 2026-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='academic/videos/'),
        ),
    ]
