# Generated by Django 6.0 on 2025-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notice',
            name='class_name',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], default='General', max_length=2),
            preserve_default=False,
        ),
    ]
