# Generated by Django 6.0 on 2025-12-31 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_rename_body_notice_description_notice_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='class_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
