# Generated by Django 6.0 on 2026-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_notice_date_alter_notice_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Saturday', max_length=20),
        ),
    ]
