# Generated by Django 6.0 on 2025-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student')], max_length=50),
        ),
    ]
